### ISSUE TITLE
Champ A20 issue?

### ISSUE THREAD

**Issue by casey-c** [casey-c/Bestiary#1]
There might be an issue with the champ moveset for A20. Need to double check. Leaving an issue since I can't work on it right now and don't want to forget to double check.

**Comment by L0to** [comment]
Yes his moveset isn't correct. For example his anger buff is only listed as +6 strength at A20 but it should be +12. Please update! Otherwise great mod.

**Comment by casey-c** [comment]
Thanks to polyakovmyu, should be fixed by the next release!

https://github.com/casey-c/Bestiary/pull/4
